source "https://rubygems.org"

gem 'activerecord', '5.2.3', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3'
gem 'pry'
gem 'rest-client'
gem 'json'
gem 'faker'
gem 'rspec'
